name:                learn-haskell2
version:             0.1.0.0
github:              "ogkuzmin/learn-haskell2"
license:             BSD3
author:              "Oleg Kuzmin"
maintainer:          "ogkuzmin@gmail.com"
copyright:           "None"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ogkuzmin/learn-haskell2#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  learn-haskell2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learn-haskell2

tests:
  learn-haskell2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learn-haskell2
